
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MULT = 6;
  public static final int LCBRACK = 11;
  public static final int LPAREN = 7;
  public static final int RCBRACK = 12;
  public static final int INT = 29;
  public static final int MINUS = 5;
  public static final int STRARRAY = 23;
  public static final int STATIC = 25;
  public static final int RPAREN = 8;
  public static final int NOT = 32;
  public static final int SEMICOLON = 13;
  public static final int LT = 16;
  public static final int BOOL = 30;
  public static final int COMMA = 3;
  public static final int CLASS = 17;
  public static final int PLUS = 4;
  public static final int LSBRACK = 9;
  public static final int MAIN = 26;
  public static final int IF = 21;
  public static final int THIS = 37;
  public static final int DOT = 14;
  public static final int ID = 27;
  public static final int RSBRACK = 10;
  public static final int INTARRAY = 31;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int EQUAL = 15;
  public static final int TRUE = 35;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int NUMBER = 28;
  public static final int VOID = 24;
  public static final int ELSE = 22;
  public static final int WHILE = 20;
  public static final int SYSOUT = 39;
  public static final int PUBLIC = 2;
  public static final int EXTENDS = 18;
  public static final int LEN = 34;
  public static final int FALSE = 36;
  public static final int AND2 = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "COMMA",
  "PLUS",
  "MINUS",
  "MULT",
  "LPAREN",
  "RPAREN",
  "LSBRACK",
  "RSBRACK",
  "LCBRACK",
  "RCBRACK",
  "SEMICOLON",
  "DOT",
  "EQUAL",
  "LT",
  "CLASS",
  "EXTENDS",
  "RETURN",
  "WHILE",
  "IF",
  "ELSE",
  "STRARRAY",
  "VOID",
  "STATIC",
  "MAIN",
  "ID",
  "NUMBER",
  "INT",
  "BOOL",
  "INTARRAY",
  "NOT",
  "AND2",
  "LEN",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "SYSOUT"
  };
}

